rules = [
  DisableSyntax,
  LeakingImplicitClassVal,
  NoValInForComprehension,
  RedundantSyntax
]

DisableSyntax.noNulls = true
DisableSyntax.noReturns = true
DisableSyntax.noThrows = true
DisableSyntax.noAsInstanceOf = false
